<?php

namespace common\helpers;

class Permission
{
    const VIEW_PRESENTATION = 'VIEW_PRESENTATION';
    const VIEW_OWN_PRESENTATION = 'VIEW_OWN_PRESENTATION';
    const CREATE_PRESENTATION = 'CREATE_PRESENTATION';
    const MANAGE_PRESENTATION = 'MANAGE_PRESENTATION';
    const MANAGE_OWN_PRESENTATION = 'MANAGE_OWN_PRESENTATION';
    
    const VIEW_COMMENT = 'VIEW_COMMENT';
    const CREATE_COMMENT = 'CREATE_COMMENT';
    
    const MANAGE_USERS = 'MANAGE_USERS';
    
    const MANAGE_CATEGORIES = 'MANAGE_CATEGORIES';
}
